### ISSUE TITLE
Quit aqua bg and insert the bg of the error pages, it's more beautiful

### ISSUE THREAD

**Issue by Dualthink** [Rover656/KoolBrowse-Site#1]
This is the bg : ![bg](https://cloud.githubusercontent.com/assets/21276394/18319909/0056cf68-7528-11e6-8647-19328efba1fe.jpg)

and this is the line of the code `<body background="bg.jpg">`

**Comment by Rover656** [comment]
yes, great idea! doing now, also I am on discord

**Comment by Rover656** [comment]
@Dualthink it's implemented
